version: "3.8"

services:
  backfin:
    build: .
    image: backfin
    container_name: backfin
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Mount your repo's data directory into container so DB is accessible
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: >
      gunicorn --worker-class=eventlet --workers=1 --bind=0.0.0.0:8000 --timeout=120 liveserver:app

  replay-service:
    build: .
    image: backfin
    container_name: backfin-replay
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Mount your repo's data directory into container so DB is accessible
      - ./data:/app/data
    depends_on:
      - backfin
    restart: unless-stopped
    command: >
      python replay.py --continuous --interval 60 --batch 200
