"""
Export OpenAPI specification from the FastAPI application
This script generates the OpenAPI JSON spec without using AI
"""
import json
import sys
from pathlib import Path

# Add parent directory to path
sys.path.append(str(Path(__file__).parent))

def export_openapi_spec():
    """Export OpenAPI specification to JSON file"""
    try:
        # Import the FastAPI app
        from app import app
        
        # Get the OpenAPI schema (automatically generated by FastAPI)
        openapi_schema = app.openapi()
        
        # Save to file
        output_file = Path(__file__).parent / "openapi.json"
        with open(output_file, "w") as f:
            json.dump(openapi_schema, f, indent=2)
        
        print(f"✅ OpenAPI specification exported to: {output_file}")
        print(f"📊 Endpoints found: {len(openapi_schema.get('paths', {}))}")
        print(f"📋 Schemas defined: {len(openapi_schema.get('components', {}).get('schemas', {}))}")
        
        # Print summary of endpoints
        print("\n📍 API Endpoints:")
        for path, methods in openapi_schema.get('paths', {}).items():
            for method in methods.keys():
                if method.upper() in ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']:
                    summary = methods[method].get('summary', 'No description')
                    print(f"  {method.upper():6} {path:60} - {summary}")
        
        return output_file
        
    except Exception as e:
        print(f"❌ Error exporting OpenAPI spec: {e}")
        import traceback
        traceback.print_exc()
        return None


def export_openapi_yaml():
    """Export OpenAPI specification to YAML file"""
    try:
        import yaml
        from app import app
        
        # Get the OpenAPI schema
        openapi_schema = app.openapi()
        
        # Save to YAML file
        output_file = Path(__file__).parent / "openapi.yaml"
        with open(output_file, "w") as f:
            yaml.dump(openapi_schema, f, default_flow_style=False, sort_keys=False)
        
        print(f"✅ OpenAPI YAML specification exported to: {output_file}")
        return output_file
        
    except ImportError:
        print("⚠️  PyYAML not installed. Install with: pip install pyyaml")
        return None
    except Exception as e:
        print(f"❌ Error exporting OpenAPI YAML: {e}")
        return None


if __name__ == "__main__":
    print("🚀 Exporting OpenAPI Specification from FastAPI App")
    print("=" * 70)
    
    # Export JSON (always available)
    json_file = export_openapi_spec()
    
    # Export YAML (if PyYAML is installed)
    print("\n" + "=" * 70)
    yaml_file = export_openapi_yaml()
    
    print("\n" + "=" * 70)
    print("✨ Export complete!")
    
    if json_file:
        print(f"\n📄 JSON Spec: {json_file}")
        print(f"   View at: https://editor.swagger.io/")
        print(f"   Or use: curl http://localhost:5002/openapi.json")
    
    if yaml_file:
        print(f"\n📄 YAML Spec: {yaml_file}")
    
    print("\n💡 You can also access the interactive docs at:")
    print(f"   - Swagger UI: http://localhost:5002/docs")
    print(f"   - ReDoc: http://localhost:5002/redoc")
    print(f"   - OpenAPI JSON: http://localhost:5002/openapi.json")
